version: '3.8'

services:
  symfony-app:
    build: 
      context: .   
      dockerfile: Dockerfile
    container_name: symfony-linux
    volumes:
      - .:/var/www/symfony  
    working_dir: /var/www/symfony
    ports:
      - "8000:8000"
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    command: tail -f /dev/null
    networks:
      - symfony-network
    depends_on:      
      - mysql

  mysql:
    image: mysql:8.0    
    container_name: mysql_sym
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dawdb
    volumes:
      - ./dataMYSQL:/var/lib/mysql  
    ports:
      - "3306:3306"
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge
