security:
    # Configuración de firewalls (sin autenticación)
    firewalls:
        # Firewall para las páginas públicas (por ejemplo, la página de citas)
        public:
            pattern: ^/(citas|home|contacto)
            security: false  # No se requiere autenticación para estas páginas

    # No necesitas configuración de control de acceso si no hay roles o autenticación
    # access_control: []
