security:
  password_hashers:
    App\Entity\User: 'auto' 

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: dni

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

   
    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      jwt: ~

  access_control:



